bootstrap-prefix.sh: exclude pip from Python build #715974
Pip is not needed but it fails to build due to lack of pyexpat,
which generates a non-fatal error during boostrap of stage1:

    ModuleNotFoundError: No module named 'pyexpat'
    make: *** [Makefile:1102: install] Error 1
    ??? Python failed to install *sigh* continuing anyway
    * Python bootstrapped

Closes: https://bugs.gentoo.org/715974
Signed-off-by: Alexei Colin <acolin@isi.edu>
Signed-off-by: Fabian Groffen <grobian@gentoo.org>